import Link from "next/link";
import { ArrowLeft, Binary } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-black text-white">
      {/* Background */}
      <div className="fixed inset-0 pointer-events-none">
        <div
          className="absolute inset-0 opacity-30"
          style={{
            backgroundImage:
              "radial-gradient(rgba(255,255,255,0.03) 1px, transparent 1px)",
            backgroundSize: "32px 32px",
          }}
        />
      </div>

      {/* Nav */}
      <nav className="relative z-10 border-b border-gray-900">
        <div className="max-w-3xl mx-auto px-8 py-5 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5">
            <Binary className="h-4 w-4 text-violet-400" />
            <span className="font-bold">D2D</span>
          </Link>
          <Link
            href="/"
            className="flex items-center gap-1.5 text-sm text-gray-500 hover:text-white transition-colors"
          >
            <ArrowLeft className="h-3.5 w-3.5" />
            Back to home
          </Link>
        </div>
      </nav>

      {/* Content */}
      <main className="relative z-10 max-w-3xl mx-auto px-8 py-20">
        <p className="text-sm text-violet-400 font-mono mb-4">/terms</p>
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-4">
          Terms of Service
        </h1>
        <p className="text-sm text-gray-600 mb-12">
          Last updated: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
        </p>

        <div className="prose prose-invert prose-gray max-w-none space-y-8 text-gray-400 leading-relaxed text-sm">
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing and using D2D (&ldquo;the Service&rdquo;), you agree
              to be bound by these Terms of Service. If you do not agree to
              these terms, do not use the Service. D2D is an open-source project
              licensed under the MIT License.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">
              2. Description of Service
            </h2>
            <p>
              D2D is a browser-based deterministic UI compiler that transforms
              hand-drawn wireframe sketches into production-ready React +
              Tailwind CSS components. The code generation pipeline runs
              entirely in your browser — no data is sent to external AI
              services.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">
              3. User Accounts
            </h2>
            <p>
              You may create an account using Google OAuth or email. You are
              responsible for maintaining the security of your account
              credentials. You must provide accurate information when creating
              your account.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">
              4. Generated Code Ownership
            </h2>
            <p>
              All code generated by D2D belongs to you. You are free to use,
              modify, distribute, and commercialize any code generated through
              the Service without restriction. D2D claims no ownership or
              licensing rights over generated output.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">
              5. Your Content
            </h2>
            <p>
              You retain all rights to your wireframe designs, style guide
              configurations, and project data. Your canvas data is stored in
              our database (powered by Convex) for the purpose of providing the
              Service (project persistence, auto-save). We do not sell, share,
              or use your designs for training purposes.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">
              6. Privacy & Data Processing
            </h2>
            <p>
              The code generation pipeline runs entirely in your browser. Your
              wireframe shapes are not transmitted to any external API for
              generation purposes. Project data (shapes, style guide, viewport)
              is stored in Convex for persistence. Authentication is handled via
              Google OAuth through Convex Auth.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">
              7. Subscription & Payments
            </h2>
            <p>
              D2D offers free and paid tiers. The Free tier includes unlimited
              code generations. Paid tiers (Pro) provide additional features
              including unlimited projects, the recipe system, and priority
              support. Payments are processed through Razorpay. You may cancel
              your subscription at any time.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">
              8. Open Source License
            </h2>
            <p>
              The D2D source code is available under the MIT License at{" "}
              <Link
                href="https://github.com/mevirajsheoran/d2d-compiler"
                target="_blank"
                className="text-violet-400 hover:text-violet-300 underline"
              >
                github.com/mevirajsheoran/d2d-compiler
              </Link>
              . The MIT License applies to the source code. These Terms of
              Service apply to the hosted Service at d2d.dev (or applicable
              domain).
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">
              9. Acceptable Use
            </h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>
                Use the Service to generate code for illegal or harmful purposes
              </li>
              <li>Attempt to reverse-engineer the hosted backend services</li>
              <li>
                Create automated systems that abuse the Service infrastructure
              </li>
              <li>Impersonate other users or misrepresent your identity</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">
              10. Disclaimer of Warranties
            </h2>
            <p>
              The Service is provided &ldquo;as is&rdquo; without warranties of
              any kind. While we strive for high-quality code generation, the
              generated code is provided as a starting point and may require
              modification for your specific use case. You are responsible for
              reviewing and testing any generated code before deploying to
              production.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">
              11. Limitation of Liability
            </h2>
            <p>
              D2D and its creator shall not be liable for any indirect,
              incidental, special, or consequential damages arising from your
              use of the Service or any generated code.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">
              12. Changes to Terms
            </h2>
            <p>
              We reserve the right to modify these terms at any time. Changes
              will be posted on this page with an updated date. Continued use of
              the Service after changes constitutes acceptance of the revised
              terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">
              13. Contact
            </h2>
            <p>
              For questions about these terms, please open an issue on our{" "}
              <Link
                href="https://github.com/mevirajsheoran/d2d-compiler/issues"
                target="_blank"
                className="text-violet-400 hover:text-violet-300 underline"
              >
                GitHub repository
              </Link>
              .
            </p>
          </section>
        </div>

        {/* Back link */}
        <div className="mt-16 pt-8 border-t border-gray-900">
          <Link
            href="/"
            className="text-sm text-gray-500 hover:text-white transition-colors flex items-center gap-1.5"
          >
            <ArrowLeft className="h-3.5 w-3.5" />
            Back to D2D
          </Link>
        </div>
      </main>
    </div>
  );
}